{{- if and .Values.autoscaling.enabled (gt (int .Values.replicaCount) 1) }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "mastyf-ai.fullname" . }}
  labels:
    {{- include "mastyf-ai.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "mastyf-ai.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    {{- if .Values.autoscaling.customMetric.enabled }}
    - type: Pods
      pods:
        metric:
          name: mastyf_ai_proxy_requests_total
        target:
          type: AverageValue
          averageValue: {{ .Values.autoscaling.customMetric.averageRequestsPerSecond | quote }}
    {{- end }}
{{- end }}
