version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      dev-dependencies:
        patterns:
          - "@types/*"
          - "vitest"
          - "eslint*"
  - package-ecosystem: npm
    directory: /apps/cloud
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /packages/core
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
