/**
 * Data Fetcher — real-time data provider for the TUI dashboard.
 * Connects to a running MCP Guardian dashboard server via WebSocket
 * and HTTP REST API for live data. Zero mock/estimated data.
 */
import * as http from 'http';

export interface TuiData {
  overview: OverviewData;
  security: SecurityData;
  cost: CostData;
  health: HealthData;
  ai: AiData;
  audit: AuditData;
  policy: PolicyData;
  instances: InstanceData[];
}

export interface OverviewData {
  totalInstances: number;
  activeInstances: number;
  totalRequests: number;
  blockedRequests: number;
  passRate: number;
  totalCostUsd: number;
  burnRatePerHour: number;
  avgLatencyMs: number;
  activeServers: number;
  lastUpdated: string;
}

export interface SecurityData {
  servers: { name: string; score: number; cves: number; critical: number; auth: boolean }[];
  overallScore: number;
  worstOffenders: string[];
  activeThreats: number;
  lastScan: string;
}

export interface CostData {
  servers: { name: string; tokens: number; cost: number; trend: string }[];
  totalCost: number;
  projectedMonthly: number;
  budgetAlerts: string[];
  pricingModel: string;
}

export interface HealthData {
  servers: { name: string; latency: number; successRate: number; tools: number; circuitBreaker: string }[];
  atRisk: string[];
  avgLatency: number;
  totalTools: number;
}

export interface AiData {
  suggestions: any[];
  baselines: any[];
  learningState: { adaptiveThreshold: number; truePositiveRate: number; falsePositiveRate: number; moduleWeights: Record<string, number> };
  threats: any[];
  report: any;
}

export interface AuditData {
  events: any[];
  total: number;
  blocked: number;
  passed: number;
  flagged: number;
}

export interface PolicyData {
  mode: string;
  activeRules: number;
  autoGeneratedRules: string[];
  rules: any[];
}

export interface InstanceData {
  instanceId: string;
  instanceName: string;
  status: string;
  hostname: string;
  version: string;
  lastHeartbeat: string;
  totalRequests: number;
  blockedRequests: number;
  totalCostUsd: number;
  avgLatencyMs: number;
}

export class DataFetcher {
  private dashboardUrl: string;
  private ws: WebSocket | null = null;
  private wsUrl: string;
  private cache: TuiData | null = null;
  private listeners: Set<() => void> = new Set();
  private wsConnected = false;
  private reconnectTimer: ReturnType<typeof setTimeout> | null = null;

  constructor(dashboardUrl?: string) {
    this.dashboardUrl = (dashboardUrl || process.env['GUARDIAN_DASHBOARD_URL'] || 'http://localhost:4000').replace(/\/$/, '');
    this.wsUrl = this.dashboardUrl.replace(/^http/, 'ws') + '/ws';
  }

  /** Get current cached data */
  getData(): TuiData | null {
    return this.cache;
  }

  /** Subscribe to data updates */
  onChange(callback: () => void): () => void {
    this.listeners.add(callback);
    return () => this.listeners.delete(callback);
  }

  /** Notify all listeners */
  private notify(): void {
    for (const listener of this.listeners) {
      try { listener(); } catch { /* ignore listener errors */ }
    }
  }

  /** Connect WebSocket for real-time updates */
  connectWebSocket(): void {
    try {
      // Using global WebSocket available in Node 22+
      const WS = (globalThis as any).WebSocket;
      if (!WS) {
        this.fallbackToHttp();
        return;
      }

      this.ws = new WS(this.wsUrl);
      this.ws.onopen = () => {
        this.wsConnected = true;
        // Subscribe to all channels
        if (this.ws?.readyState === 1) {
          this.ws.send(JSON.stringify({
            type: 'subscribe',
            channels: ['ai', 'audit', 'metrics', 'logs', 'instances', 'policy', 'health', 'cost'],
          }));
        }
      };

      this.ws.onmessage = (event: MessageEvent) => {
        try {
          const msg = JSON.parse(event.data.toString());
          this.handleWsMessage(msg);
        } catch { /* ignore parse errors */ }
      };

      this.ws.onclose = () => {
        this.wsConnected = false;
        this.scheduleReconnect();
      };

      this.ws.onerror = () => {
        this.wsConnected = false;
        this.fallbackToHttp();
      };
    } catch {
      this.fallbackToHttp();
    }
  }

  /** Fall back to HTTP polling when WebSocket is unavailable */
  private fallbackToHttp(): void {
    this.fetchAll().catch(() => {
      // Will retry on next poll interval
    });
  }

  /** Schedule WebSocket reconnection */
  private scheduleReconnect(): void {
    if (this.reconnectTimer) return;
    this.reconnectTimer = setTimeout(() => {
      this.reconnectTimer = null;
      this.connectWebSocket();
    }, 5000);
  }

  /** Handle incoming WebSocket messages */
  private handleWsMessage(msg: any): void {
    const cache = this.cache;
    if (!cache) return;

    switch (msg.type) {
      case 'ai:suggestions':
        cache.ai.suggestions = msg.payload?.suggestions || [];
        break;
      case 'ai:baselines':
        cache.ai.baselines = msg.payload?.baselines || [];
        break;
      case 'ai:state':
        cache.ai.learningState = msg.payload?.state || cache.ai.learningState;
        break;
      case 'ai:threats':
        cache.ai.threats = msg.payload?.threats || [];
        break;
      case 'ai:report':
        cache.ai.report = msg.payload?.report || null;
        break;
      case 'audit:events':
        if (msg.payload?.events) {
          cache.audit.events = msg.payload.events;
        }
        break;
      case 'metrics:live':
        if (msg.payload?.instances) {
          cache.instances = msg.payload.instances;
        }
        break;
    }

    this.notify();
  }

  /** Fetch all data from HTTP API */
  async fetchAll(): Promise<TuiData> {
    const [overview, security, cost, health, ai, audit, policy, instances] = await Promise.allSettled([
      this.fetchJson('/api/aggregate/metrics'),
      this.fetchJson('/api/security'),
      this.fetchJson('/api/cost'),
      this.fetchJson('/api/health'),
      this.fetchJson('/api/ai/report'),
      this.fetchJson('/api/aggregate/audit'),
      this.fetchJson('/api/policy'),
      this.fetchJson('/api/instances'),
    ]);

    this.cache = {
      overview: this.parseOverview(overview.status === 'fulfilled' ? overview.value : null),
      security: this.parseSecurity(security.status === 'fulfilled' ? security.value : null),
      cost: this.parseCost(cost.status === 'fulfilled' ? cost.value : null),
      health: this.parseHealth(health.status === 'fulfilled' ? health.value : null),
      ai: this.parseAi(ai.status === 'fulfilled' ? ai.value : null),
      audit: this.parseAudit(audit.status === 'fulfilled' ? audit.value : null),
      policy: this.parsePolicy(policy.status === 'fulfilled' ? policy.value : null),
      instances: this.parseInstances(instances.status === 'fulfilled' ? instances.value : null),
    };

    this.notify();
    return this.cache;
  }

  /** Fetch JSON from an API endpoint */
  private async fetchJson(path: string): Promise<any> {
    try {
      const response = await fetch(`${this.dashboardUrl}${path}`, {
        signal: AbortSignal.timeout(5000),
      });
      if (!response.ok) return null;
      return response.json();
    } catch {
      return null;
    }
  }

  /** Start periodic HTTP polling fallback */
  startPolling(intervalMs: number = 3000): ReturnType<typeof setInterval> {
    return setInterval(() => {
      this.fetchAll().catch(() => {});
    }, intervalMs);
  }

  /** Parse overview data */
  private parseOverview(data: any): OverviewData {
    return {
      totalInstances: data?.totalInstances || 0,
      activeInstances: data?.activeInstances || 0,
      totalRequests: data?.totalRequests || 0,
      blockedRequests: data?.blockedRequests || 0,
      passRate: data?.totalRequests > 0 ? ((data.passedRequests || 0) / data.totalRequests) * 100 : 100,
      totalCostUsd: data?.totalCost || 0,
      burnRatePerHour: data?.burnRatePerHour || 0,
      avgLatencyMs: data?.avgLatencyMs || 0,
      activeServers: data?.activeServers || 0,
      lastUpdated: data?.lastUpdated || new Date().toISOString(),
    };
  }

  /** Parse security data */
  private parseSecurity(data: any): SecurityData {
    return {
      servers: data?.serverReports || [],
      overallScore: data?.overallScore || 0,
      worstOffenders: data?.worstOffenders || [],
      activeThreats: data?.activeThreats || 0,
      lastScan: data?.lastScan || 'N/A',
    };
  }

  /** Parse cost data */
  private parseCost(data: any): CostData {
    return {
      servers: data?.serverReports || [],
      totalCost: data?.totalCost || 0,
      projectedMonthly: data?.projectedMonthly || 0,
      budgetAlerts: data?.budgetAlerts || [],
      pricingModel: data?.pricingModel || 'unknown',
    };
  }

  /** Parse health data */
  private parseHealth(data: any): HealthData {
    return {
      servers: data?.serverReports || [],
      atRisk: data?.atRisk || [],
      avgLatency: data?.avgLatency || 0,
      totalTools: data?.totalTools || 0,
    };
  }

  /** Parse AI data */
  private parseAi(data: any): AiData {
    return {
      suggestions: data?.suggestions || [],
      baselines: data?.baselines || [],
      learningState: data?.learningState || { adaptiveThreshold: 0.85, truePositiveRate: 0, falsePositiveRate: 0, moduleWeights: {} },
      threats: data?.threats || [],
      report: data?.report || null,
    };
  }

  /** Parse audit data */
  private parseAudit(data: any): AuditData {
    return {
      events: data?.events || [],
      total: data?.total || 0,
      blocked: data?.blocked || 0,
      passed: data?.passed || 0,
      flagged: data?.flagged || 0,
    };
  }

  /** Parse policy data */
  private parsePolicy(data: any): PolicyData {
    return {
      mode: data?.mode || 'none',
      activeRules: data?.activeRules || 0,
      autoGeneratedRules: data?.autoGeneratedRules || [],
      rules: data?.rules || [],
    };
  }

  /** Parse instances data */
  private parseInstances(data: any): InstanceData[] {
    if (Array.isArray(data)) {
      return data.map((inst: any) => ({
        instanceId: inst.instance_id || inst.instanceId || 'unknown',
        instanceName: inst.instance_name || inst.instanceName || 'unknown',
        status: inst.status || 'unknown',
        hostname: inst.hostname || inst.host_name || 'unknown',
        version: inst.version || 'unknown',
        lastHeartbeat: inst.last_heartbeat || inst.lastHeartbeat || 'N/A',
        totalRequests: inst.total_requests || inst.totalRequests || 0,
        blockedRequests: inst.blocked_requests || inst.blockedRequests || 0,
        totalCostUsd: inst.total_cost_usd || inst.totalCostUsd || 0,
        avgLatencyMs: inst.avg_latency_ms || inst.avgLatencyMs || 0,
      }));
    }
    return [];
  }

  /** Stop and clean up */
  stop(): void {
    if (this.ws) {
      this.ws.close();
      this.ws = null;
    }
    if (this.reconnectTimer) {
      clearTimeout(this.reconnectTimer);
      this.reconnectTimer = null;
    }
    this.listeners.clear();
  }
}