/**
 * Data Fetcher — reads from HistoryDatabase + AI files + LLM for descriptive analysis.
 */
import { HistoryDatabase } from '../database/history-db.js';
import { readFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { homedir } from 'os';
import { fileURLToPath } from 'url';
import { LlmAssistant } from '../ai/llm-assistant.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const HOME = homedir();
const GUARDIAN_DIR = resolve(HOME, '.mcp-guardian');

export interface TuiData {
  overview: OverviewData; security: SecurityData; cost: CostData;
  health: HealthData; ai: AiData; audit: AuditData; policy: PolicyData; instances: InstanceData[];
}
export interface OverviewData {
  totalInstances: number; activeInstances: number; totalRequests: number;
  blockedRequests: number; passRate: number; totalCostUsd: number;
  burnRatePerHour: number; avgLatencyMs: number; activeServers: number; lastUpdated: string;
}
export interface SecurityData {
  servers: { name: string; score: number; cves: number; critical: number; auth: boolean }[];
  overallScore: number; worstOffenders: string[]; activeThreats: number; lastScan: string;
}
export interface CostData {
  servers: { name: string; tokens: number; cost: number; trend: string }[];
  totalCost: number; projectedMonthly: number; budgetAlerts: string[]; pricingModel: string;
}
export interface HealthData {
  servers: { name: string; latency: number; successRate: number; tools: number; circuitBreaker: string }[];
  atRisk: string[]; avgLatency: number; totalTools: number;
}
export interface AiData {
  suggestions: any[]; baselines: any[];
  learningState: { adaptiveThreshold: number; truePositiveRate: number; falsePositiveRate: number; moduleWeights: Record<string, number> };
  threats: any[]; report: any;
  analysis: string;
}
export interface AuditData { events: any[]; total: number; blocked: number; passed: number; flagged: number; }
export interface PolicyData { mode: string; activeRules: number; autoGeneratedRules: string[]; rules: any[]; }
export interface InstanceData {
  instanceId: string; instanceName: string; status: string; hostname: string;
  version: string; lastHeartbeat: string; totalRequests: number;
  blockedRequests: number; totalCostUsd: number; avgLatencyMs: number;
}

const PRICING = { input: 2.50, output: 10.00 };

export class DataFetcher {
  private db: HistoryDatabase;
  private cache: TuiData | null = null;
  private listeners: Set<() => void> = new Set();
  private pollTimer: ReturnType<typeof setInterval> | null = null;
  private llm: LlmAssistant;
  private lastAnalysis = '';

  constructor(_dashboardUrl?: string) {
    this.db = new HistoryDatabase();
    this.llm = new LlmAssistant();
  }

  getData(): TuiData | null { return this.cache; }
  onChange(cb: () => void): () => void { this.listeners.add(cb); return () => { this.listeners.delete(cb); }; }
  private notify() { for (const l of this.listeners) { try { l(); } catch {} } }
  connectWebSocket() {}

  async fetchAll(): Promise<TuiData> {
    try {
      const servers = await this.db.getDistinctScannedServers();

      let allRecords: any[] = [];
      let totalRequests = 0, totalInput = 0, totalOutput = 0, totalAll = 0, totalLatency = 0;
      for (const srv of servers) {
        const recs = await this.db.getCallRecordsForServer(srv);
        for (const r of recs) {
          totalRequests++;
          totalInput += (r as any).requestTokens || 0;
          totalOutput += (r as any).responseTokens || 0;
          totalAll += (r as any).totalTokens || 0;
          totalLatency += (r as any).durationMs || 0;
          allRecords.push(r);
        }
      }

      const costUSD = (totalInput / 1_000_000) * PRICING.input + (totalOutput / 1_000_000) * PRICING.output;
      const avgLatency = totalRequests > 0 ? Math.round(totalLatency / totalRequests) : 0;

      const secReports: any[] = []; let totalScore = 0;
      for (const srv of servers) {
        const scan = await this.db.getLatestSecurityScan(srv);
        if (scan) {
          const s = scan as any;
          secReports.push({ name: s.server_name || srv, score: s.score || 0, cves: s.cve_count || 0,
            critical: (s.details?.cves || []).filter((c: any) => c.severity === 'CRITICAL').length,
            auth: !!(s.details?.authStatus?.hasAuthentication) });
          totalScore += s.score || 0;
        } else { secReports.push({ name: srv, score: 0, cves: 0, critical: 0, auth: false }); }
      }

      const costReports: any[] = [];
      for (const srv of servers) {
        const srecs = allRecords.filter((r: any) => r.serverName === srv);
        const tokens = srecs.reduce((s: number, r: any) => s + (r.totalTokens || 0), 0);
        const inT = srecs.reduce((s: number, r: any) => s + (r.requestTokens || 0), 0);
        const outT = srecs.reduce((s: number, r: any) => s + (r.responseTokens || 0), 0);
        costReports.push({ name: srv, tokens, cost: (inT / 1e6) * PRICING.input + (outT / 1e6) * PRICING.output, trend: 'flat' });
      }

      const healthReports: any[] = [];
      for (const srv of servers) {
        const srecs = allRecords.filter((r: any) => r.serverName === srv);
        const sLat = srecs.length > 0 ? Math.round(srecs.reduce((s: number, r: any) => s + ((r as any).durationMs || 0), 0) / srecs.length) : 0;
        const sr = await this.db.getRecentSuccessRate(srv);
        healthReports.push({ name: srv, latency: sLat, successRate: (sr || 1) * 100, tools: 3, circuitBreaker: 'closed' });
      }

      const auditEvents = allRecords.slice(0, 15).map((r: any) => ({
        timestamp: r.timestamp || '', server_name: r.serverName, tool_name: r.toolName,
        action: 'pass', request_tokens: r.requestTokens || 0, total_tokens: r.totalTokens || 0,
      }));

      let aiState = { adaptiveThreshold: 0.82, truePositiveRate: 0.67, falsePositiveRate: 0.33, moduleWeights: { baseline: 0.95, cost: 0.87, threat: 1.0, assist: 1.0 } as Record<string, number> };
      let suggestions: any[] = [];
      let threats: any[] = [];

      try {
        const aiPath = resolve(GUARDIAN_DIR, '.ai-learning.json');
        if (existsSync(aiPath)) {
          const st = JSON.parse(readFileSync(aiPath, 'utf-8'));
          aiState.adaptiveThreshold = st.adaptiveThreshold || 0.85;
          aiState.truePositiveRate = st.truePositiveRate || 0;
          aiState.falsePositiveRate = st.falsePositiveRate || 0;
          if (st.moduleWeights) aiState.moduleWeights = st.moduleWeights;
          if (st.outcomes) suggestions = st.outcomes;
        }
      } catch {}

      try {
        const threatPath = resolve(GUARDIAN_DIR, '.threat-state.json');
        if (existsSync(threatPath)) {
          const st = JSON.parse(readFileSync(threatPath, 'utf-8'));
          if (st.ids && Array.isArray(st.ids)) {
            threats = st.ids.map((id: string) => ({
              id, source: id.startsWith('osv-') ? 'OSV' : id.startsWith('gh-') ? 'GitHub' : 'NVD',
              severity: 'HIGH',
            }));
          }
        }
      } catch {}

      // Use cached analysis first so TUI renders immediately
      let analysis = this.lastAnalysis || '';

      // Fire LLM analysis in background (non-blocking)
      const topTools = this.getTopTools(allRecords);
      const securityIssues = secReports.filter((r: any) => r.score < 70).map((r: any) => r.name);
      const prompt = this.buildAnalysisPrompt(totalRequests, costUSD, avgLatency, servers.length, threats, aiState, topTools, securityIssues, allRecords);
      this.llm.generate(
        'You are an MCP security operations analyst. Write a concise 3-4 sentence security/cost assessment of this MCP proxy deployment. Be direct, specify actual risks, and recommend one action. No disclaimers.',
        prompt
      ).then(result => {
        if (result?.text) {
          this.lastAnalysis = result.text;
          if (this.cache) { this.cache.ai.analysis = result.text; this.notify(); }
        }
      }).catch(() => {});

      this.cache = {
        overview: { totalInstances: 1, activeInstances: 1, totalRequests, blockedRequests: 0, passRate: 100, totalCostUsd: costUSD, burnRatePerHour: totalRequests > 0 ? (costUSD / totalRequests) * 100 : 0, avgLatencyMs: avgLatency, activeServers: servers.length, lastUpdated: new Date().toISOString() },
        security: { servers: secReports, overallScore: secReports.length > 0 ? Math.round(totalScore / secReports.length) : 0, worstOffenders: secReports.filter((r: any) => r.score < 50).map((r: any) => r.name), activeThreats: threats.length, lastScan: new Date().toISOString() },
        cost: { servers: costReports, totalCost: costUSD, projectedMonthly: costUSD * 30, budgetAlerts: costUSD > 5 ? ['Monthly spend exceeding $150 budget threshold'] : [], pricingModel: 'gpt-4o ($2.50/$10.00 per 1M)' },
        health: { servers: healthReports, atRisk: healthReports.filter((h: any) => h.latency > 200 || h.successRate < 70).map((h: any) => h.name), avgLatency, totalTools: servers.length * 3 },
        ai: { suggestions, baselines: [], learningState: aiState, threats, report: null, analysis },
        audit: { events: auditEvents, total: auditEvents.length, blocked: 0, passed: auditEvents.length, flagged: 0 },
        policy: { mode: 'audit', activeRules: 0, autoGeneratedRules: [], rules: [] },
        instances: [{ instanceId: `guardian-${process.pid}`, instanceName: 'localhost', status: 'active', hostname: 'localhost', version: '2.3.24', lastHeartbeat: new Date().toISOString(), totalRequests, blockedRequests: 0, totalCostUsd: costUSD, avgLatencyMs: avgLatency }],
      };
    } catch {
      this.cache = {
        overview: { totalInstances: 0, activeInstances: 0, totalRequests: 0, blockedRequests: 0, passRate: 100, totalCostUsd: 0, burnRatePerHour: 0, avgLatencyMs: 0, activeServers: 0, lastUpdated: '' },
        security: { servers: [], overallScore: 0, worstOffenders: [], activeThreats: 0, lastScan: 'N/A' },
        cost: { servers: [], totalCost: 0, projectedMonthly: 0, budgetAlerts: [], pricingModel: '' },
        health: { servers: [], atRisk: [], avgLatency: 0, totalTools: 0 },
        ai: { suggestions: [], baselines: [], learningState: { adaptiveThreshold: 0.85, truePositiveRate: 0, falsePositiveRate: 0, moduleWeights: {} }, threats: [], report: null, analysis: '' },
        audit: { events: [], total: 0, blocked: 0, passed: 0, flagged: 0 },
        policy: { mode: 'none', activeRules: 0, autoGeneratedRules: [], rules: [] },
        instances: [],
      };
    }
    this.notify();
    return this.cache;
  }

  private getTopTools(records: any[]): { name: string; count: number; totalTokens: number }[] {
    const map = new Map<string, { count: number; totalTokens: number }>();
    for (const r of records) {
      const tn = r.toolName || 'unknown';
      if (!map.has(tn)) map.set(tn, { count: 0, totalTokens: 0 });
      const e = map.get(tn)!;
      e.count++;
      e.totalTokens += (r.totalTokens || 0);
    }
    return [...map.entries()]
      .map(([name, v]) => ({ name, count: v.count, totalTokens: v.totalTokens }))
      .sort((a, b) => b.totalTokens - a.totalTokens)
      .slice(0, 5);
  }

  private buildAnalysisPrompt(
    totalRequests: number, costUsd: number, avgLatency: number,
    serverCount: number, threats: any[], aiState: any,
    topTools: { name: string; count: number }[],
    securityIssues: string[], records: any[],
  ): string {
    const toolLines = topTools.map(t => `  - ${t.name}: ${t.count} calls`).join('\n');
    const secLines = securityIssues.length > 0 ? `Security concerns: ${securityIssues.join(', ')}` : 'No critical security issues';
    const threatList = threats.slice(0, 3).map(t => t.id).join(', ');
    return `MCP Guardian deployment summary:
- ${totalRequests} total tool calls across ${serverCount} server(s)
- Total cost: $${costUsd.toFixed(4)}
- Average latency: ${avgLatency}ms
- ${threats.length} active threat intelligence entries (${threatList})
- AI self-improvement: ${Math.round(aiState.truePositiveRate * 100)}% true positive rate, threshold ${aiState.adaptiveThreshold}
- Top tools by usage:\n${toolLines || '  No tools detected'}
- ${secLines}

Provide a brief operational security and cost assessment.`;
  }

  startPolling(ms = 3000) {
    this.pollTimer = setInterval(() => { this.fetchAll().catch(() => {}); }, ms);
    return this.pollTimer;
  }
  stop() {
    if (this.pollTimer) { clearInterval(this.pollTimer); this.pollTimer = null; }
    this.listeners.clear();
    try { this.db.close(); } catch {}
  }
}