import { GovernanceSnapshot } from './data-collector.js';
import { BaselineProfile } from './baseline-learner.js';
import { CrossLayerInsight, TemporalPattern } from './pattern-recognizer.js';
import { LearningState } from './self-improvement.js';
import { PolicyRule } from '../policy/policy-types.js';

export interface ComprehensiveReport {
  timestamp: string;
  executiveSummary: {
    overallScore: number;
    totalCost: number;
    topRisks: string[];
    activeServers: number;
    blockedCalls: number;
    recommendations: string[];
  };
  security: {
    serverReports: { name: string; score: number; cves: number; critical: number; auth: boolean }[];
    worstOffenders: string[];
  };
  cost: {
    serverReports: { name: string; tokens: number; cost: number; trend: string }[];
    projectedMonthly: number;
    budgetAlerts: string[];
  };
  health: {
    serverReports: { name: string; latency: number; success: number; tools: number }[];
    atRisk: string[];
  };
  behavioral: {
    baselines: { server: string; tool: string; sampleCount: number; avgTokens: number; avgLatency: number }[];
    anomalies: string[];
  };
  patterns: {
    crossLayerInsights: { type: string; severity: string; description: string; confidence: number }[];
    temporal: { hour: number; volume: number; avgTokens: number }[];
  };
  policy: {
    activeRules: string[];
    autoGeneratedRules: string[];
    prunedRules: string[];
  };
  aiState: {
    adaptiveThreshold: number;
    truePositiveRate: number;
    falsePositiveRate: number;
    moduleWeights: Record<string, number>;
  };
  recommendations: { priority: number; action: string; impact: string; confidence: number }[];
}

export class ComprehensiveReporter {
  generateFullReport(
    snapshot: GovernanceSnapshot,
    baselines: BaselineProfile[],
    insights: CrossLayerInsight[],
    temporal: TemporalPattern[],
    autoRules: string[],
    learning: LearningState,
    pruneList: string[],
  ): ComprehensiveReport {
    // ── Executive Summary ──────────────────────────────────
    const totalSecurityScore = snapshot.securityReports.length > 0
      ? Math.round(snapshot.securityReports.reduce((s, r) => s + r.score, 0) / snapshot.securityReports.length)
      : 0;

    const topRisks: string[] = [];
    const worstOffenders = snapshot.securityReports
      .filter(s => s.score < 50)
      .map(s => s.serverName);
    for (const s of snapshot.securityReports.filter(s => s.score < 30)) {
      topRisks.push(`${s.serverName}: security score ${s.score}/100, ${s.cves.length} CVEs`);
    }
    const unhealthy = snapshot.healthReports.filter(h => h.successRate < 0.5);
    for (const h of unhealthy) {
      topRisks.push(`${h.serverName}: unhealthy (${(h.successRate * 100).toFixed(0)}% success)`);
    }

    const recommendations: { priority: number; action: string; impact: string; confidence: number }[] = [];

    // ── Security ───────────────────────────────────────────
    const securityReports = snapshot.securityReports.map(s => ({
      name: s.serverName,
      score: s.score,
      cves: s.cves.length,
      critical: s.cves.filter(c => c.severity === 'CRITICAL').length,
      auth: s.authStatus?.hasAuthentication || false,
    }));

    // ── Cost ───────────────────────────────────────────────
    const costReports = snapshot.costReports.map(c => ({
      name: c.serverName,
      tokens: c.tokensUsed,
      cost: c.estimatedCostUSD,
      trend: 'flat' as string,
    }));

    const totalCost = costReports.reduce((s, c) => s + c.cost, 0);
    const projectedMonthly = totalCost * 30;
    const budgetAlerts: string[] = [];

    // ── Health ─────────────────────────────────────────────
    const healthReports = snapshot.healthReports.map(h => ({
      name: h.serverName,
      latency: h.latencyMs,
      success: h.successRate * 100,
      tools: h.toolCount,
    }));
    const atRisk = snapshot.healthReports
      .filter(h => h.successRate < 0.7 || h.overloadWarning)
      .map(h => h.serverName);

    // ── Behavioral ─────────────────────────────────────────
    const baselineReport = baselines.map(b => ({
      server: b.serverName,
      tool: b.toolName,
      sampleCount: b.sampleCount,
      avgTokens: Math.round(b.avgTokens),
      avgLatency: Math.round(b.avgLatencyMs),
    }));

    // ── Patterns ───────────────────────────────────────────
    const patternReport = insights.map(i => ({
      type: i.type,
      severity: i.severity,
      description: i.description,
      confidence: i.confidence,
    }));
    const temporalReport = temporal
      .filter(t => t.callVolume > 0)
      .map(t => ({ hour: t.hour, volume: t.callVolume, avgTokens: t.avgTokens }));

    // ── Generate recommendations ───────────────────────────
    for (const s of worstOffenders) {
      recommendations.push({
        priority: 1,
        action: `Update or isolate ${s} — security score ${snapshot.securityReports.find(r => r.serverName === s)?.score || 0}`,
        impact: 'Prevent CVE exploitation',
        confidence: 0.9,
      });
    }
    for (const h of unhealthy) {
      recommendations.push({
        priority: 2,
        action: `Investigate health issues on ${h.serverName} (${(h.successRate * 100).toFixed(0)}% success)`,
        impact: 'Restore service reliability',
        confidence: 0.8,
      });
    }
    for (const i of insights) {
      if (i.severity === 'critical' && i.suggestedRule) {
        recommendations.push({
          priority: 1,
          action: i.description,
          impact: 'Cross-layer risk mitigation',
          confidence: i.confidence,
        });
      }
    }
    if (pruneList.length > 0) {
      recommendations.push({
        priority: 3,
        action: `Consider pruning ${pruneList.length} ineffective auto-generated rules: ${pruneList.slice(0, 3).join(', ')}`,
        impact: 'Reduce policy noise',
        confidence: 0.7,
      });
    }

    return {
      timestamp: snapshot.timestamp,
      executiveSummary: {
        overallScore: totalSecurityScore,
        totalCost,
        topRisks: topRisks.slice(0, 5),
        activeServers: snapshot.metadata.activeServers.length,
        blockedCalls: snapshot.metadata.blockedCalls,
        recommendations: recommendations.slice(0, 5).map(r => r.action),
      },
      security: { serverReports: securityReports, worstOffenders },
      cost: { serverReports: costReports, projectedMonthly, budgetAlerts },
      health: { serverReports: healthReports, atRisk },
      behavioral: { baselines: baselineReport, anomalies: [] },
      patterns: { crossLayerInsights: patternReport, temporal: temporalReport },
      policy: { activeRules: [], autoGeneratedRules: autoRules, prunedRules: pruneList },
      aiState: {
        adaptiveThreshold: learning.adaptiveThreshold,
        truePositiveRate: learning.truePositiveRate,
        falsePositiveRate: learning.falsePositiveRate,
        moduleWeights: learning.moduleWeights,
      },
      recommendations,
    };
  }

  toMarkdown(report: ComprehensiveReport): string {
    const lines: string[] = [];
    lines.push(`# MCP Guardian — AI-Driven Comprehensive Report`);
    lines.push(`**${report.timestamp}** | Score: ${report.executiveSummary.overallScore}/100 | Cost: $${report.executiveSummary.totalCost.toFixed(4)}`);
    lines.push('');
    lines.push('## Executive Summary');
    lines.push(`- Active servers: ${report.executiveSummary.activeServers}`);
    lines.push(`- Blocked calls: ${report.executiveSummary.blockedCalls}`);
    lines.push(`- AI threshold: ${report.aiState.adaptiveThreshold.toFixed(2)}`);
    if (report.executiveSummary.topRisks.length > 0) {
      lines.push('### Top Risks');
      for (const r of report.executiveSummary.topRisks) lines.push(`- ⚠️ ${r}`);
    }
    lines.push('');
    lines.push('## Security');
    for (const s of report.security.serverReports) {
      const icon = s.score < 30 ? '🔴' : s.score < 60 ? '🟡' : '🟢';
      lines.push(`- ${icon} **${s.name}**: ${s.score}/100, ${s.cves} CVEs (${s.critical} critical), auth: ${s.auth ? '✅' : '❌'}`);
    }
    lines.push('');
    lines.push('## Cost');
    for (const c of report.cost.serverReports) {
      lines.push(`- **${c.name}**: ${c.tokens.toLocaleString()} tokens, $${c.cost.toFixed(4)}`);
    }
    lines.push(`**Projected monthly:** $${report.cost.projectedMonthly.toFixed(2)}`);
    lines.push('');
    lines.push('## Health');
    for (const h of report.health.serverReports) {
      lines.push(`- **${h.name}**: ${h.latency}ms, ${h.success.toFixed(0)}% success, ${h.tools} tools`);
    }
    lines.push('');
    lines.push('## Cross-Layer Insights');
    for (const p of report.patterns.crossLayerInsights) {
      lines.push(`- [${p.severity}] ${p.description} (confidence: ${(p.confidence * 100).toFixed(0)}%)`);
    }
    lines.push('');
    lines.push('## AI Self-Improvement');
    lines.push(`- Adaptive threshold: ${report.aiState.adaptiveThreshold.toFixed(2)}`);
    lines.push(`- True positive rate: ${(report.aiState.truePositiveRate * 100).toFixed(0)}%`);
    lines.push(`- False positive rate: ${(report.aiState.falsePositiveRate * 100).toFixed(0)}%`);
    lines.push('');
    lines.push('## Recommendations');
    for (const r of report.recommendations) {
      lines.push(`1. **[P${r.priority}]** ${r.action} — ${r.impact} (${(r.confidence * 100).toFixed(0)}%)`);
    }
    return lines.join('\n');
  }
}