/**
 * LLM Assistant — Local Ollama integration for the Adaptive AI Policy Engine.
 *
 * Provides NL→YAML rule generation, anomaly explanation, threat analysis,
 * and cross-layer insight synthesis using locally-running free models.
 *
 * No API keys. No cloud costs. No data leaves the machine.
 * All calls are best-effort — graceful fallback if Ollama is unavailable.
 */
import { Logger } from '../utils/logger.js';

export interface LlmAssistantConfig {
  model: string;
  ollamaUrl: string;
  timeoutMs: number;
  enabled: boolean;
  maxRetries: number;
}

const DEFAULT_CONFIG: LlmAssistantConfig = {
  model: process.env['GUARDIAN_LLM_MODEL'] || 'qwen3:8b',
  ollamaUrl: process.env['OLLAMA_URL'] || 'http://localhost:11434',
  timeoutMs: parseInt(process.env['GUARDIAN_LLM_TIMEOUT_MS'] || '30000', 10),
  enabled: process.env['GUARDIAN_LLM_ENABLED'] !== 'false',
  maxRetries: 2,
};

export interface LlmResponse {
  text: string;
  model: string;
  tokensUsed: number;
  durationMs: number;
}

export class LlmAssistant {
  private config: LlmAssistantConfig;

  constructor(config?: Partial<LlmAssistantConfig>) {
    this.config = { ...DEFAULT_CONFIG, ...config };
  }

  /** Check if Ollama is reachable */
  async healthCheck(): Promise<boolean> {
    try {
      const response = await fetch(`${this.config.ollamaUrl}/api/tags`, {
        signal: AbortSignal.timeout(5000),
      });
      return response.ok;
    } catch {
      return false;
    }
  }

  /**
   * Generate completion using local Ollama model.
   * Returns null if unavailable or disabled.
   */
  async generate(systemPrompt: string, userPrompt: string): Promise<LlmResponse | null> {
    if (!this.config.enabled) return null;

    let lastError: Error | null = null;
    for (let attempt = 0; attempt <= this.config.maxRetries; attempt++) {
      try {
        const startTime = Date.now();
        const response = await fetch(`${this.config.ollamaUrl}/api/generate`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            model: this.config.model,
            prompt: `${systemPrompt}\n\n${userPrompt}`,
            stream: false,
            options: {
              temperature: 0.1,
              num_predict: 1024,
            },
          }),
          signal: AbortSignal.timeout(this.config.timeoutMs),
        });

        if (!response.ok) {
          throw new Error(`Ollama returned ${response.status}`);
        }

        const data = await response.json() as any;
        const durationMs = Date.now() - startTime;

        return {
          text: (data.response || '').trim(),
          model: data.model || this.config.model,
          tokensUsed: data.eval_count || 0,
          durationMs,
        };
      } catch (err: any) {
        lastError = err;
        if (attempt < this.config.maxRetries) {
          await new Promise(r => setTimeout(r, 1000 * (attempt + 1)));
        }
      }
    }

    Logger.debug(`[LlmAssistant] Failed after ${this.config.maxRetries + 1} attempts: ${lastError?.message}`);
    return null;
  }

  /**
   * Generate a YAML policy rule from a natural language goal.
   */
  async generatePolicyRule(goal: string, availableTools?: string[]): Promise<{
    yaml: string;
    explanation: string;
  } | null> {
    const systemPrompt = `You are an MCP (Model Context Protocol) security policy generator.
Your task is to convert a natural-language policy goal into a valid YAML policy rule for MCP Guardian.
Output ONLY a JSON object with "yaml" (the YAML rule block) and "explanation" (why this rule).

YAML format:
  - name: rule-name
    description: "rule description"
    action: block | flag | pass
    tools:
      deny: [tool_name]
    patterns:
      - 'regex_pattern'
    maxCallsPerMinute: number
    maxTokens: number
    rbac:
      scopes: [scope_name]

Available tools: ${availableTools?.join(', ') || 'unknown'}

Never wrap the JSON in markdown code blocks. Output ONLY valid JSON.`;

    const result = await this.generate(
      systemPrompt,
      `Generate a policy rule for: ${goal}`
    );

    if (!result) return null;

    try {
      const parsed = JSON.parse(result.text);
      return {
        yaml: parsed.yaml || '',
        explanation: parsed.explanation || 'Rule generated by LLM',
      };
    } catch {
      Logger.debug('[LlmAssistant] Failed to parse policy rule JSON from LLM response');
      return null;
    }
  }

  /**
   * Explain an anomaly detected by BaselineLearner in human language.
   */
  async explainAnomaly(params: {
    serverName: string;
    toolName: string;
    metric: string;
    zScore: number;
    expectedValue: number;
    actualValue: number;
    historicalSamples: number;
  }): Promise<string | null> {
    const systemPrompt = `You are an MCP security analyst. Explain anomalies concisely in one sentence.
Focus on the operational impact and what the anomaly might indicate.
Be direct and specific. No disclaimers or suggestions.`;

    const userPrompt =
      `Anomaly detected on "${params.serverName}" using tool "${params.toolName}":
- Metric: ${params.metric}
- Z-score (deviation): ${params.zScore.toFixed(2)}
- Expected value: ${params.expectedValue}
- Actual value: ${params.actualValue}
- Historical samples: ${params.historicalSamples}

Explain this anomaly:`;

    const result = await this.generate(systemPrompt, userPrompt);
    return result?.text || null;
  }

  /**
   * Analyze a CVE and suggest targeted blocking rules.
   */
  async analyzeThreat(params: {
    cveId: string;
    severity: string;
    description: string;
    affectedPackage: string;
  }): Promise<{
    impact: string;
    suggestedPatterns: string[];
    action: string;
  } | null> {
    const systemPrompt = `You are an MCP security threat analyst.
Analyze CVE impacts and suggest blocking patterns and remediation.
Output ONLY a JSON object with "impact" (one-line summary),
"suggestedPatterns" (array of regex strings), and "action" (block|flag|pass).
Never wrap the JSON in markdown code blocks. Output ONLY valid JSON.`;

    const userPrompt =
      `Analyze CVE-${params.cveId} (${params.severity}):
Description: ${params.description}
Affected package: ${params.affectedPackage}`;

    const result = await this.generate(systemPrompt, userPrompt);
    if (!result) return null;

    try {
      return JSON.parse(result.text);
    } catch {
      return null;
    }
  }

  /**
   * Synthesize cross-layer insights into an executive summary.
   */
  async synthesizeInsights(insights: Array<{
    type: string;
    severity: string;
    description: string;
  }>): Promise<string | null> {
    if (insights.length === 0) return null;

    const systemPrompt = `You are a senior SRE/security analyst.
Synthesize multiple cross-layer insights into a concise 2-3 sentence executive summary.
Focus on interconnected risks and top-priority actions. Be direct.`;

    const insightText = insights
      .map((i, idx) => `${idx + 1}. [${i.severity}] ${i.description}`)
      .join('\n');

    const result = await this.generate(
      systemPrompt,
      `Synthesize these cross-layer governance insights:\n\n${insightText}`
    );

    return result?.text || null;
  }

  /** Check if LLM is enabled and available */
  isAvailable(): boolean {
    return this.config.enabled;
  }

  getModel(): string {
    return this.config.model;
  }
}